remote_theme: tuur29/pages-themes-cayman
title: "Tanner Meininger’s ePortfolio"
description: "Capstone portfolio showcasing software engineering, algorithmic, and database enhancements"
show_downloads: true          # shows download buttons for your zip files
hide_first_title: false       # usually keep false
darkmode: false               # enable or disable dark mode toggle
colors:
  gradient_left: "#155799"
  gradient_right: "#159957"
  link: "#1e6bb8"
