remote_theme: tuur29/pages-themes-cayman
title: "Tanner Meininger’s ePortfolio"
description: "Capstone portfolio showcasing software engineering, algorithmic, and database enhancements"
show_downloads: true
hide_first_title: false
darkmode: true
colors:
  gradient_left: "#155799"
  gradient_right: "#159957"
  link: "#1e6bb8"
